server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://wish:wish123@localhost:27017/wishnotification?authSource=wishnotification

      auto-index-creation: true
  
    
  codec:
    max-in-memory-size: 16MB

  webflux:
    base-path: /api

# Firebase Configuration
firebase:
  config-path: classpath:service-account-key.json

# Web Push Configuration
webpush:
  public-key: BHy2SrmleeiRQ7SXuDAcSQE2-t5G1hr2vU8MfR9TTWl3wpu--yiGiR9ak-ad0ASSlgseJG3BrHbd1CBsLriWa5s
  private-key: huVJXf_XYE4xag1unkHTXTQK7-Clx0UAO0N77myaASA
  subject: mailto:wishful@gmail.com

# clothes Service 연동 추가
clothes-service:
  base-url: http://localhost:8081/api/clothes

# Weather Service 연동 (추가)
weather-service:
  base-url: http://localhost:8082/api/v1

notification:
  daily:
    enabled: true
    cron: "0 0 9 * * *"
    lat: 37.5665
    lon: 126.9780
    location-label: "서울(시청)"
    zone: Asia/Seoul
    mobile-topic: daily-weather
    default-user-id: 1  # ← 추천 이미지 가져올 대표 사용자
    mobile-title: "오늘의 날씨"
    web-title: "오늘의 날씨"
    click-action: "http://localhost:8083"
# Logging
logging:
  level:
    today.wishwordrobe: DEBUG
    com.google.firebase: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true