server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    mongodb:

      uri: ${MONGODB_URI_NOTIFICATION}
      #  uri: mongodb://wish:wish123@localhost:27017/wishnotification?authSource=wishnotification&maxPoolSize=1000&minPoolSize=100&maxWaitTime=5000&socketTimeout=10000&connectTimeout=5000
      auto-index-creation: true
    
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379 
      
  codec:
    max-in-memory-size: 16MB

  webflux:
    base-path: /api

# Firebase Configuration
firebase:
  config-path: file:/app/service-account-key.json

# Web Push Configuration
webpush:
  public-key: ${WEBPUSH_PUBLIC_KEY}
  private-key: ${WEBPUSH_PRIVATE_KEY}
  subject: mailto:wishful@gmail.com

# clothes Service 연동 추가
clothes-service:
  base-url: http://localhost:8081/api/clothes

# Weather Service 연동 (추가)
weather-service:
  base-url: http://localhost:8082/api/v1


# Logging
logging:
  level:
    today.wishwordrobe: DEBUG
    com.google.firebase: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: /actuator
  server:
    port: 9091
  prometheus:
    metrics:
      export:
        enabled: true
      # enable: 
      #   jvm: false
      #   system: false
      #   process: false 
      #   executor: false
      #   logback: false