version: '3.8'

services:
  #gateway service
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - clothes-service
      - weather-service
      - notification-service
    networks:
      - wishwordrobe-network
    restart: unless-stopped
  # Clothes Service - 의류 관리 서비스 (WebMVC)
  clothes-service:
    build:
      context: ./clothes-service
      dockerfile: Dockerfile
    container_name: clothes-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - clothes-uploads:/app/uploads
    networks:
      - wishwordrobe-network
    restart: unless-stopped


  # Weather Service - 날씨 정보 서비스 (WebFlux)
  weather-service:
    build:
      context: ./weather-service
      dockerfile: Dockerfile
    container_name: weather-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - wishwordrobe-network
    restart: unless-stopped
  # Notification Service - 알림 서비스 (WebFlux)
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - ./notification-service/src/main/resources/service-account-key.json:/app/service-account-key.json:ro

    networks:
      - wishwordrobe-network
    restart: unless-stopped

  # Frontend - Vue.js Application
  wishwardrobe-front:
    build:
      context: /home/ubuntu/wishwardrobe-front
      args:
        - VUE_APP_KAKAO_JS_KEY: ${VUE_APP_KAKAO_JS_KEY}
      dockerfile: Dockerfile
    container_name: wishwardrobe-front
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - gateway-service
    networks:
      - wishwordrobe-network
    restart: unless-stopped

networks:
  wishwordrobe-network:
    driver: bridge

volumes:
  clothes-uploads:
