spring:
  datasource:

    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  
  webmvc:
    base-path: /api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

  services:
    weather:
      url: http://weather-service:8082/api/v1

file:
  upload-dir: /app/uploads
  uploadDir: /app/uploads
  uploadFiles: /app/uploads

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30m




# JWT Configuration
# jwt:
#   issuer: wishful@gmail.com
#   secret_key: iwish

# Logging
logging:
  level:
    today.wishwordrobe: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.amqp: DEBUG

